/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This schema describes version 20210202 of the Catalog Metadata Standard
 */
export interface Catalog20210202 {
  /**
   * Descriptive metadata properties of a Catalog record
   */
  body: {
    /**
     * This property defines the calendar version of the schema so that consumers can correctly parse the json
     */
    version: string;
    /**
     * Title of the track
     */
    title: string;
    /**
     * Name of the artist who created the track
     */
    artist: string;
    /**
     * An optional property for describing the track
     */
    description: string | null;
    /**
     * Length of the audio file in seconds (must be > 1ms)
     */
    duration: number;
    /**
     * MimeType of the audio file. Only lossless formats (aif, wav, flac) are supported.
     */
    mimeType: "audio/aif" | "audio/flac" | "audio/wav";
    /**
     * Denotes whether the artwork is a separate NFT or is embedded into the Catalog record
     */
    isArtworkNft: boolean;
    /**
     * Information about the cover art if it isn't an NFT
     */
    artworkDetail: {
      /**
       * Pointer to the cover art for the record (must be a valid http/https url)
       */
      uri: string;
      /**
       * SHA-256 hash of the cover art at the time of mint
       */
      hash: string;
      /**
       * MimeType of the cover art
       */
      mimeType: "image/jpeg" | "image/pjpeg" | "image/png";
    } | null;
    /**
     * Information about the cover art if it is an NFT
     */
    artworkDetailNft: {
      /**
       * Ethereum network that the cover art NFT exists on
       */
      chainId: 1 | 4;
      /**
       * Address of the factory contract that was used to mint the cover art NFT
       */
      contractAddress: string;
      /**
       * Token ID of the cover art NFT
       */
      tokenId: number;
    } | null;
  };
  /**
   * Information used to verify the authenticity of the record
   */
  seal: {
    /**
     * The result of the Catalog public key signing the body of the record metadata
     */
    signature: string;
    /**
     * Catalog's public key used to sign the record metadata
     */
    publicKey: "0xc236541380fc0C2C05c2F2c6c52a21ED57c37952";
  };
}
