/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This schema describes version 20210202 of the Catalog Metadata Standard
 */
export interface Catalog20210202 {
  /**
   * Descriptive metadata properties of a Catalog record
   */
  body: {
    /**
     * This property defines the calendar version of the schema so that consumers can correctly parse the json
     */
    version: string;
    /**
     * Title of the track
     */
    title: string;
    /**
     * Name of the artist who created the track
     */
    artist: string;
    /**
     * An optional property for describing the track
     */
    description: string;
    /**
     * Length of the audio file in milliseconds
     */
    duration: number;
    /**
     * MimeType of the audio file. Only lossless formats (aif, wav, flac) are supported.
     */
    mimeType: string;
    /**
     * MimeType of the audio file. Only lossless formats (aif, wav, flac) are supported.
     */
    artwork: {
      /**
       * Denotes whether the artwork is its own NFT or is embedded into the Catalog record
       */
      isNft: boolean;
      /**
       * Pointer to the cover art for the record. This can only be either a http/https URI or zNFT ID.
       */
      uri: string;
      /**
       * SHA-256 hash of the cover art at the time of mint
       */
      hash: string;
      /**
       * MimeType of the cover art
       */
      mimeType: string;
      /**
       * Ethereum network that the cover art NFT exists on
       */
      chainId: number;
      /**
       * Address of the factory contract that was used to mint the cover art NFT
       */
      contractAddress: string;
      /**
       * Token ID of the cover art NFT
       */
      tokenId: number;
      [k: string]: unknown;
    };
  };
  /**
   * Information used to verify the authenticity of the record
   */
  seal: {
    /**
     * The result of the Catalog public key signing the body of the record metadata
     */
    signature: string;
    /**
     * Catalog's public key used to sign the record metadata
     */
    publicKey: string;
  };
}
